server:
  port: 8080
  servlet:
    application-display-name: /
spring:
  datasource:
    name: dataSource
    driver-class-name:
    url: jdbc:mysql://localhost:3306/ant?useUnicode=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
